baseURL = "https://www.paulofili.com"
languageCode = "en-us"
title = "Paul Ofili"
theme = "hugo-theme-console"
disqusShortname = "paulofili"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false
  linkedin = false
  twitter = false
  

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"

  [[params.navlinks]]
  name = "projects/"
  url = "projects/"