baseURL = "https://gracious-brattain-674cd3.netlify.app/"
languageCode = "en-us"
title = "Paul Ofili"
theme = "hugo-theme-console"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true
  linkedin = false
  twitter = false
  

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"

  [[params.navlinks]]
  name = "projects/"
  url = "projects/"